language: python
python:
  - "3.9"
  # PyPy versions
  - "pypy3"  # currently Python 3.9.0,  PyPy 7.1.1-beta0
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script: pytest